### ISSUE TITLE
HTTP 500: "Undefined index: CONTENT_TYPE"

### ISSUE THREAD

**Issue by adityamenon** [Pasvaz/laravel-juploader#1]
I followed the instructions in the README verbatim, installed and reinstalled the bundle and tried to do something on my own, but I am always stopped by this error:

```
Unhandled Exception

Message:

Undefined index: CONTENT_TYPE
Location:

C:\wamp\www\ongoing\project\bundles\vendor\juploader\libraries\UploadHandler.php on line 751
```

The main difference I noticed is that the bundle's demo causes a GET request to be sent to `/upload/upload`, but the same code in my views causes a POST request. I am unable to even understand where to begin debugging :(

**Comment by adityamenon** [comment]
I am very sorry. I am using a tabbed multistep form interface, and I noticed I was trying to initialize the wrong form.

I have successfully set it up and it is working perfectly. Thank you _so_ much for saving me TONS of work with this bundle.

You're a rockstar!

**Comment by Pasvaz** [comment]
No problem, I'm glad you appreciated it.
