### ISSUE TITLE
Class 'Uploader\Javascripter' not found

### ISSUE THREAD

**Issue by asivaneswaran** [Pasvaz/laravel-juploader#3]
I get that error when I include:
{{ Uploader\Javascripter::activate_uploader() }}

Any ideas why?

Thanks,
Ara

**Comment by Pasvaz** [comment]
Does the included example work? May I see your source code? I have no enough information to get an idea.

**Comment by asivaneswaran** [comment]
No when I type http://127.0.0.1/upload, I get a 404 not found page.

The source code is this:
@layout('layouts/admin')

@section('content')
    <ul class="breadcrumb br_styled no_space">
        <li>
            <a href="index.html">Dashboard</a> <span class="divider">/</span>
        </li>  
        <li class="active">Forms - wizard</li>
    </ul> 
    <ul class="page_info">
        <li><h2>Forms - wizard</h2></li>
        <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li>
     </ul>
    <div class="span12 no_space form_align">
        <div class="widget">
            <header>
                <h3>Form wizard</h3>
                <ul class="toggle_content">  
                    <li class="arrow"><a href="#">Toggle Content</a></li>
                </ul>
            </header>
            <section class="welly group">
                <div id="wizard" class="swMain">

```
                <!-- Tabs -->
                <ul class="anchor">
                    <li><a href="#step-1" class="disabled">
                        <label class="stepNumber">1</label>
                        <span class="stepDesc">
                            Verify<br />
                            <small>Verify requests</small>
                        </span>
                    </a></li>
                    <li><a href="#step-2" class="selected">
                        <label class="stepNumber">2</label>
                        <span class="stepDesc">
                            Upload<br />
                            <small>Upload necessary files</small>
                        </span>
                    </a></li>
                    <li><a href="#step-3" class="disabled">
                        <label class="stepNumber">3</label>
                        <span class="stepDesc">
                            Update<br />
                            <small>Update the database</small>
                        </span>
                    </a></li>
                    <li><a href="#step-4" class="disabled">
                            <label class="stepNumber">4</label>
                            <span class="stepDesc">
                                Report<br />
                                <small>Answer requests</small>
                            </span>
                    </a></li>
                </ul>
                <!-- End tabs -->

                <!-- Steps -->
                <div class="stepContainer" style="height: 302px;">

                    <!-- Step 2 (Upload files) -->
                    <div id="step-2" class="content" style="display: block; left: 0px;"> 
                        <h2 class="StepTitle">Step 2: Upload files</h2>
                        {{ 
                            Uploader\Javascripter::with_option('url','/upload/dbupload')
                            ->with_option('formId','dbfileupload')
                            ->activate_uploader() 
                        }}
                    </div>
                </div>

                <!-- Action bar -->
                <div class="actionBar">
                    <a href="#" class="buttonNext">Next</a>
                    <a href="#" class="buttonPrevious buttonDisabled">Previous</a>
                </div>

            </div>
        </section>
    </div>
</div>  
```

@endsection

@section('scripts')
{{ Asset::container('bootstrapper')->styles() }}
{{ Asset::container('juploader')->styles() }}
{{ Asset::container('juploader-gallery')->styles() }}

{{ Asset::container('bootstrapper')->scripts() }}
{{ Asset::container('juploader')->scripts() }}
{{ Asset::container('juploader-gallery')->scripts() }}
{{ Uploader\Javascripter::activate_uploader() }}
@endsection

Thanks,
Ara

**Comment by Pasvaz** [comment]
Does you bundles.php include the following:

``` php
'juploader' => array('handles' => 'upload'),
```

Also, consider to put `auto=true` if the uploader is served outside the `'handles'` location

**Comment by asivaneswaran** [comment]
Oh I forgot the auto-true!!!

Thanks,
But I still got a problem.

Instead of having a form, I end up having this:
{{ Uploader\Javascripter::with_option('url','/upload/dbupload') ->with_option('formId','dbfileupload') ->activate_uploader() }}

Any ideas why?

Thanks,
Ara

**Comment by Pasvaz** [comment]
What do you mean? I'm not sure to get it.
If the code between the brackets is not rendered maybe you forgot to use the .blade.php extension.

**Comment by asivaneswaran** [comment]
Yeah the code between the brackets are not rendered.

But if I return something with the controller and I put them between brackets, it works. But not the code for the uploader....

**Comment by Pasvaz** [comment]
Can you post the whole code using a service like pastebin or even jsfiddler, plunker or whatever allows the code to be entirely displayed? Generally if the code between {{}} is not rendered it means that it doesn't pass troughtt blade.

**Comment by asivaneswaran** [comment]
Here it is:
http://pastebin.com/WF5isJKg

**Comment by Pasvaz** [comment]
Change the curly brackets with the `<?php ?>` you cannot use the blade sintax on multiple lines.
If you want to use Blade then put everything on one row:

```
{{ Uploader\Javascripter::with_option('url','/upload/dbupload')->with_option('formId','dbfileupload')->activate_uploader()}}
```

**Comment by asivaneswaran** [comment]
Thanks, it works!

Just another question, the URL to route, do I need to change it?
http://pastebin.com/e0Q1WPDb Line 65

**Comment by Pasvaz** [comment]
it depends where the uploader controller sits. You don't need to change it unless you want to develop your own controller, the demo include a controller in that location, actually it includes 2 controllers: `/upload/dbupload` and `/upload/upload` check the routes.php file inside the juploader bundle folder.

**Comment by asivaneswaran** [comment]
Inside the controllers folders I only have the dbupload file

**Comment by Pasvaz** [comment]
The second controller is handled directly by the routes.php, it was done on purpose in order to demostrate both methods.

**Comment by asivaneswaran** [comment]
Oh ok.

So I changed the upload directory and now I get and Error Not found every time I try and upload....

**Comment by Pasvaz** [comment]
Again, if you don't provide the code or some logs it's impossible to understand what's going on.

**Comment by asivaneswaran** [comment]
This is in my view file:
http://pastebin.com/aZAwgCeN

And I changed the settings in the settings file:
        'script_url' => URL::to_route('upload'),
        'upload_dir' => path('public').'public/datas/',
        'upload_url' => URL::base().'public/datas/',

**Comment by Pasvaz** [comment]
The javascript still points to the uploader at upload/dbupload

**Comment by asivaneswaran** [comment]
I removed that part.

I am left with the following: 
http://pastebin.com/Kz21cWCm

I still get the Not Found Error.

Thanks,
Ara

**Comment by Pasvaz** [comment]
Both the javascript and the php must point to the controller location, please check the official jquery-uploader documentation in order to understand how it works: https://github.com/blueimp/jQuery-File-Upload/wiki/Setup

**Comment by sanmarino** [comment]
Hi. I am having the same problem that you solved before.
I think I have all correctly but I get the Class 'Uploader\Javascripter' not found error.

I followed all the installation proccess and my view has the following:

@section('scripts')
{{ Asset::container('bootstrapper')->styles() }}
{{ Asset::container('juploader')->styles() }}
{{ Asset::container('juploader-gallery')->styles() }}

{{ Asset::container('bootstrapper')->scripts() }}
{{ Asset::container('juploader')->scripts() }}
{{ Asset::container('juploader-gallery')->scripts() }}
//the following line is my code in just one row but here (on github editor) is showed in a pair.
{{ Uploader\Javascripter::with_option('url','/uploas/dbupload')->with_option('formId','dbfileupload')->activate_uploader()}}
@endsection

```
<!-- HTML5 Shiv
================================================== -->
<script src="js/jquery.modernizr.js"></script>
```

</head>

<div class="container ajax">
    
    <div class="page-header clearfix">
        <div class="seven columns row">
        <h1>El <br /> relaxing cup <br/>project</h1>
        </div>

```
    <div class="eight columns row">
        <div class="widget widget_text">

            <h3 class="widget-title right">About el proyecto</h3>

            <div class="textwidget justify">

                <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

                </p>
                <a href="#" class="button large coral"><strong>Compartir mi café</strong></a>
            </div><!--/ .textwidget-->
```

<form id="fileupload" action="{{ URL::to_route('upload') }}" method="POST" enctype="multipart/form-data">
                {{Uploader\ButtonBar::create()}}
                <p class="message-form-message">
                    <textarea name="message" required="" placeholder="Message *"></textarea>    
                </p>
                <p class="form-submit">
               <a href="#" class="button large coral">Button</a>
               <a href="#" class="button large lightgrey">Button</a>
                </p>
            <div class="hide contact-form-responce"><p></p></div>
            </form>

```
        {{ Uploader\Templater::showAll() }}
        </div>
    </div>
```

I hope you can help me.

Thank you
